Update deploy-webiste.yml

diff --git a/.github/deploy-webiste.yml b/.github/deploy-webiste.yml
--- a/.github/deploy-webiste.yml
+++ b/.github/deploy-webiste.yml
@@ -18,9 +18,19 @@ jobs:
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-    - name: Create Azure Container Registry
+    - name: Check if ACR exists
+      id: acr-check
       run: |
-        az acr create --name ${{ secrets.ACR_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --sku Basic
+        az acr show --name ${{ secrets.ACR_NAME }} --resource-group myrg2024 || echo "ACR_NOT_FOUND" > result.txt
+        if [[ -f result.txt ]]; then echo "ACR not found, creating..."; else echo "ACR found, skipping creation."; fi
+        cat result.txt
+
+    - name: Create Azure Container Registry (ACR) if not exists
+      run: |
+        if [[ -f result.txt && $(cat result.txt) == "ACR_NOT_FOUND" ]]; then
+          echo "Creating Azure Container Registry..."
+          az acr create --name ${{ secrets.ACR_NAME }} --resource-group myrg2024 --sku Basic --admin-enabled true
+        fi
 
     - name: Build and Push Docker Image to ACR
       run: |
@@ -31,7 +41,7 @@ jobs:
     - name: Deploy to Azure Container Instance
       run: |
         az container create \
-          --resource-group ${{ secrets.RESOURCE_GROUP }} \
+          --resource-group myrg2024 \
           --name myWebsiteContainer \
           --image ${{ secrets.ACR_NAME }}.azurecr.io/mywebsite:latest \
           --cpu 1 \
